name: documentation

on:
  pull_request:
    branches: [content]
  push:
    branches: [content]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Release to GitHub Pages
        env:
          GIT_USER: ${GITHUB_ACTOR}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_BRANCH: ${GITHUB_REF_NAME}
          DEPLOYMENT_BRANCH: main
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npx docusaurus deploy
